
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * @author Amir
 */
public class ViewInquiriesByAdminGUI extends javax.swing.JFrame {

    Employee employee;
    Inquiry inq = new Inquiry();

    /**
     * Creates new form ViewInquiriesByAdminGUI
     */
    public ViewInquiriesByAdminGUI() {
        initComponents();
//        InquiriesTableGUI inquiriesTable = new InquiriesTableGUI();
    }

    public ViewInquiriesByAdminGUI(Employee emp) {
        initComponents();
        employee = emp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InquiriesJTable = new javax.swing.JTable();
        SearchLabel = new javax.swing.JLabel();
        CustIDTextField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        viewAll_InquiryBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InquiriesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Question", "Customer Name", "Customer Category", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(InquiriesJTable);
        if (InquiriesJTable.getColumnModel().getColumnCount() > 0) {
            InquiriesJTable.getColumnModel().getColumn(0).setResizable(false);
            InquiriesJTable.getColumnModel().getColumn(1).setResizable(false);
            InquiriesJTable.getColumnModel().getColumn(2).setResizable(false);
            InquiriesJTable.getColumnModel().getColumn(3).setResizable(false);
            InquiriesJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        SearchLabel.setText("Search by Customer ID");

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        viewAll_InquiryBtn.setText("View All");
        viewAll_InquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAll_InquiryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(viewAll_InquiryBtn)
                        .addGap(193, 193, 193)
                        .addComponent(SearchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CustIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(SearchBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAll_InquiryBtn)
                    .addComponent(SearchBtn))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAll_InquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAll_InquiryBtnActionPerformed
        TableModel model = new DefaultTableModel();
        int row = 0;
        int col;
        for (Inquiry i : Inquiry.viewInquiries()) {
            col = 0;
            model.setValueAt(i.getID(), row, col++);
            model.setValueAt(i.getCustName(), row, col++);
            model.setValueAt(i.getQuestion(), row, col++);
            model.setValueAt(i.getCustCategory(), row, col++);
            model.setValueAt(i.getDate(), row, col++);
            row++;
        }
        InquiriesJTable.setModel(model);
    }//GEN-LAST:event_viewAll_InquiryBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String searchTextField = CustIDTextField.getText();
        ArrayList<Inquiry> inquiriesList = inq.viewInquiriesByID(Integer.parseInt(searchTextField));
        TableModel model = new DefaultTableModel();
        int row = 0;
        int col;
        for (Inquiry i : inquiriesList) {
            col = 0;
            model.setValueAt(i.getID(), row, col++);
            model.setValueAt(i.getCustName(), row, col++);
            model.setValueAt(i.getQuestion(), row, col++);
            model.setValueAt(i.getCustCategory(), row, col++);
            model.setValueAt(i.getDate(), row, col++);
            row++;
        }
        InquiriesJTable.setModel(model);
    }//GEN-LAST:event_SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInquiriesByAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInquiriesByAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInquiriesByAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInquiriesByAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInquiriesByAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustIDTextField;
    private javax.swing.JTable InquiriesJTable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewAll_InquiryBtn;
    // End of variables declaration//GEN-END:variables
}
