
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * @author Shero
 */
public class ViewRequestGUI extends javax.swing.JFrame {

    Technician technician;

    /**
     * Creates new form ViewRequestGUI
     */
    public ViewRequestGUI() {
        initComponents();
    }

    public ViewRequestGUI(Technician tech) {
        initComponents();
        setLocationRelativeTo(null);
        technician = tech;
        
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        model.setRowCount(0);
        int row = 0;
        int col;
        
        ArrayList<Request> requests = Request.viewRequest(tech);
        if (requests.isEmpty()) {
            return;
        }
        for (Request r : requests) {
            col = 0;
            model.addRow(new Object[]{});
            model.setValueAt(r.getID(), row, col++);
            model.setValueAt(r.getCustID(), row, col++);
            model.setValueAt(r.getLocation(), row, col++);
            model.setValueAt(r.getRequestType(), row, col++);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        RequestIDTextField = new javax.swing.JTextField();
        FinalizeServiceBtn = new javax.swing.JButton();
        ConfirmCashPaymentBtn = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Requests");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Customer ID", "Address", "Request Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Request ID");

        FinalizeServiceBtn.setText("Finalize Service");
        FinalizeServiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizeServiceBtnActionPerformed(evt);
            }
        });

        ConfirmCashPaymentBtn.setText("Confirm Cash Payment");
        ConfirmCashPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmCashPaymentBtnActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RequestIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ConfirmCashPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FinalizeServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RequestIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmCashPaymentBtn)
                    .addComponent(FinalizeServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmCashPaymentBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_ConfirmCashPaymentBtnActionPerformed
        String requestID = RequestIDTextField.getText();
        if (requestID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a request id");
            return;
        }
        
        Connection conn = DatabaseSingleton.getInstance().getConnection();
        try {
            Statement stat = conn.createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM request WHERE id = " + requestID);
            if (result.next()) {
                if (!result.getString("requestType").equals("Collect Cash Payment")) {
                    JOptionPane.showMessageDialog(this, "The request type does not match the selected button");
                    return;
                }
                Request request = new Request(result.getInt(1), result.getInt(6), result.getString(2), result.getString(3), result.getString(4), LocalDateTime.now());
                ConfirmCashPaymentGUI confirmCashPaymentGUI = new ConfirmCashPaymentGUI(technician, request);
                confirmCashPaymentGUI.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Please select a request id from the ones displayed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving request from database");
        }
    }//GEN-LAST:event_ConfirmCashPaymentBtnActionPerformed

    private void FinalizeServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizeServiceBtnActionPerformed
        String requestID = RequestIDTextField.getText();
        if (requestID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a request id");
            return;
        }
        
        Connection conn = DatabaseSingleton.getInstance().getConnection();
        try {
            Statement stat = conn.createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM request WHERE id = " + requestID);
            if (result.next()) {
                if (!result.getString("requestType").equals("Service")) {
                    JOptionPane.showMessageDialog(this, "The request type does not match the selected button");
                    return;
                }
                stat.executeUpdate("DELETE FROM request WHERE id = " + requestID);
                JOptionPane.showMessageDialog(this, "Request finalized");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a request id from the ones displayed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Request does not exist in database");
        }
    }//GEN-LAST:event_FinalizeServiceBtnActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        TechnicianDashboardGUI gui = new TechnicianDashboardGUI(technician);
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRequestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmCashPaymentBtn;
    private javax.swing.JButton FinalizeServiceBtn;
    private javax.swing.JTextField RequestIDTextField;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
